@CarRental.RentalApi_HostAddress = http://localhost:5182

# CarTypes
# 0 - Compact Car
# 1 - Station Wagon
# 2 - Truck

# Compact Car

GET {{CarRental.RentalApi_HostAddress}}/checkoutcar/
Content-Type: application/json

{
  "bookingNumber": "123456",
  "carRegistrationPlate": "ABC123",
  "customerId": "123456",
  "carType": 0,
  "odometer": 1000
}

###

GET {{CarRental.RentalApi_HostAddress}}/returncar/
Content-Type: application/json

{
  "bookingNumber": "123456",
  "odometer": 1200
}

###

# Station wagon Car

GET {{CarRental.RentalApi_HostAddress}}/checkoutcar/
Content-Type: application/json

{
  "bookingNumber": "123457",
  "carRegistrationPlate": "ABC123",
  "customerId": "123456",
  "carType": 1,
  "odometer": 1000
}

###

GET {{CarRental.RentalApi_HostAddress}}/returncar/
Content-Type: application/json

{
  "bookingNumber": "123457",
  "odometer": 1200
}

###

# Truck

GET {{CarRental.RentalApi_HostAddress}}/checkoutcar/
Content-Type: application/json

{
  "bookingNumber": "123458",
  "carRegistrationPlate": "ABC123",
  "customerId": "123456",
  "carType": 0,
  "odometer": 1000
}

###

GET {{CarRental.RentalApi_HostAddress}}/returncar/
Content-Type: application/json

{
  "bookingNumber": "123458",
  "odometer": 1200
}

###
